[Interface]
Address = 10.0.0.10/24, fd00:1::10/64
PrivateKey = CLIENT_PRIVATE_KEY

[Peer]
PublicKey = VPS_PUBLIC_KEY
PresharedKey = CLIENT_PSK
Endpoint = example.com:51820
AllowedIPs = 10.0.0.0/24, fd00:1::/64, 192.168.10.0/24, fd00:10::/64, 192.168.20.0/24, fd00:20::/64
PersistentKeepalive = 25
