[Interface]
Address = 10.0.0.2/24, fd00:1::2/64
PrivateKey = FIRST_SITE_PRIVATE_KEY

PostUp = sysctl -w net.ipv4.ip_forward=1
PostUp = sysctl -w net.ipv6.conf.all.forwarding=1

[Peer]
PublicKey = VPS_PUBLIC_KEY
PresharedKey = FIRST_SITE_PSK
Endpoint = example.com:51820
AllowedIPs = 10.0.0.0/24, fd00:1::/64, 192.168.10.0/24, fd00:10::/64
PersistentKeepalive = 25
