[Interface]
Address = 10.0.0.10/24, fd00:1::10/64
PrivateKey = NAS_PRIVATE_KEY

[Peer]
PublicKey = VPS_PUBLIC_KEY
PresharedKey = NAS_PSK
Endpoint = example.com:51820
AllowedIPs = 10.0.0.0/24, fd00:1::/64, 192.168.10.0/24, fd00:10::/64
PersistentKeepalive = 25
